# Generated by Django 5.1.6 on 2025-04-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JodApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('room_type', models.CharField(max_length=100)),
                ('room_size', models.CharField(max_length=100)),
                ('set_food', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('application_status', models.CharField(choices=[('standard', 'ต้องการบริกร 1-2 คน'), ('premium', 'ต้องการบริกร 3-4 คน'), ('super premium', 'ต้องการบริกร 5-6 คน')], default='waiting', max_length=30)),
            ],
        ),
    ]
